language: php

services:
  - mysql
  
php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

sudo: required

before_install:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - mysql -e 'create database vuedo_test;'


script:
- composer install --dev --prefer-source --no-interaction
- php artisan migrate
- php artisan db:seed
- vendor/bin/phpunit tests
